# Generated by Django 4.1.4 on 2022-12-24 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='project_link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
