# Generated by Django 4.1.4 on 2022-12-29 23:13

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_portfolio_category_blog_video'),
    ]

    operations = [
       
        migrations.AlterField(
            model_name='blog',
            name='video',
            field=embed_video.fields.EmbedVideoField(null=True),
        ),
    ]
