# Generated by Django 4.1.4 on 2022-12-31 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_portfolio_category_alter_blog_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='video',
            new_name='video2',
        ),
       
    ]
