# Generated by Django 4.1.4 on 2022-12-31 16:52

import ckeditor.fields
from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_rename_video_blog_video2_remove_portfolio_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kurumsal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('hakkinda', ckeditor.fields.RichTextField()),
                ('faaliyetlerimiz', ckeditor.fields.RichTextField()),
                ('neredeyiz', ckeditor.fields.RichTextField()),
                ('iletisim_yollari', ckeditor.fields.RichTextField()),
            ],
        ),
       
        migrations.AlterField(
            model_name='blog',
            name='video2',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
