# Generated by Django 4.1.3 on 2022-12-17 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_category_slug_alter_blog_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
