# Generated by Django 4.1.4 on 2022-12-24 01:14

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_product_image2_product_image3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='portfolios')),
                ('image2', models.ImageField(null=True, upload_to='portfolios')),
                ('image3', models.ImageField(null=True, upload_to='portfolios')),
                ('description', ckeditor.fields.RichTextField()),
                ('is_active', models.BooleanField(default=False)),
                ('is_home', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('project_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('project_link', models.CharField(max_length=200)),
                ('category', models.ManyToManyField(to='app.category')),
            ],
        ),
    ]
