# Generated by Django 4.1.4 on 2022-12-29 22:15

from django.db import migrations
import django.utils.timezone
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_hizmetler_remove_portfolio_category'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='blog',
            name='video',
            field=embed_video.fields.EmbedVideoField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
